Theory LambdaPiBinderAlgebra
Ancestors
  LambdaPiTyping rich_list
Libs
  boolSimps numLib

(* Two lifts at the same cutoff compose additively.  This is the algebraic
   fact behind reverse-index context lookup when a binder is introduced. *)
Theorem lift_compose:
  !t d1 d2 c.
    lift d1 c (lift d2 c t) = lift (d2 + d1) c t
Proof
  Induct >> simp[ADD_ASSOC]
  >- (rpt gen_tac >> Cases_on `n < c` >> simp[] >> numLib.ARITH_TAC)
QED

(* Lifting once at a cutoff and immediately substituting at that same cutoff
   is an identity.  This is the key beta/substitution cancellation law. *)
Theorem subst_lift_cancel:
  !t u c.
    subst u c (lift 1 c t) = t
Proof
  Induct >> simp[]
  >- (rpt gen_tac >> Cases_on `n < c` >> simp[] >> numLib.ARITH_TAC)
QED

Theorem subst0_lift1:
  !t u.
    subst0 u (lift 1 0 t) = t
Proof
  simp[subst0_def, subst_lift_cancel]
QED

(* The newest entry in Kontroli's oldest-to-newest local-context vector is
   de Bruijn variable 0, and get_type shifts it by one binder. *)
Theorem ctx_type_extend_zero:
  !G A.
    ctx_type (G ++ [A]) 0 (lift 1 0 A)
Proof
  simp[ctx_type_def, rich_listTheory.EL_LENGTH_APPEND_0]
QED

Theorem ctx_type_empty:
  !n A. ~ctx_type [] n A
Proof
  simp[ctx_type_def]
QED

Theorem ctx_type_in_bounds:
  !G n A. ctx_type G n A ==> n < LENGTH G
Proof
  simp[ctx_type_def]
QED

Theorem ctx_type_functional:
  !G n A B.
    ctx_type G n A / ctx_type G n B ==> A = B
Proof
  simp[ctx_type_def]
QED

(* This is kept explicit for the next stack.  The full typing-substitution
   theorem must discharge it for the rewrite relation generated by accepted
   Kontroli rules rather than assume it silently. *)
Definition rewrite_substitution_closed_def:
  rewrite_substitution_closed R <=>
    !t v u c. R t v ==> R (subst u c t) (subst u c v)
End

val _ = export_theory();
